Create build-dev.yml
MForystek/beauty-supplies-store pull request #5
Opened 2023-06-18 08:53 UTC by ajamrozy

2023-06-18 09:16 UTC, ajamrozy commented
- add secrets and use them in docker compose
- add detached mode to containers

2023-07-10 17:21 UTC, MForystek requested changes

2023-07-10 17:21 UTC, MForystek commented on .github/workflows/build-dev.yml
> +    - name: Print variables
Better to delete this step

2023-07-10 17:44 UTC, MForystek commented
It would be better to change the branch name and PR name to conform with the convention

2023-07-17 18:09 UTC, MForystek approved these changes

2023-07-24 15:50 UTC, sszymiczek approved these changes

2023-07-29 08:06 UTC, merged